"use client";
import {useEffect,useMemo,useState} from "react";
import {MapPin,Compass,Search,Sparkles,LocateFixed,Clock3,Heart,ExternalLink,CalendarDays,Navigation,RefreshCw,X} from "lucide-react";
import {demoListings,type Category} from "../lib/discovery";
type LiveEvent={id:string;name:string;url:string|null;date:string|null;venue:string|null;image:string|null;source:string};
const categories:Category[]=["All","Events","Food & Drink","Activities","Nightlife","Outdoors"];
const DEFAULT_COORDS={lat:35.994,lng:-78.899};
export default function Home(){
 const [city,setCity]=useState("Durham, NC"),[category,setCategory]=useState<Category>("All"),[query,setQuery]=useState("");
 const [status,setStatus]=useState(""),[when,setWhen]=useState("Any time"),[coords,setCoords]=useState<{lat:number;lng:number}|null>(null);
 const [events,setEvents]=useState<LiveEvent[]>([]),[eventState,setEventState]=useState("idle"),[saved,setSaved]=useState<string[]>([]),[onlySaved,setOnlySaved]=useState(false);
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem("roam:saved")||"[]"))}catch{setSaved([])}},[]);
 const toggleSaved=(id:string)=>setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem("roam:saved",JSON.stringify(next));return next});
 const listings=useMemo(()=>demoListings.filter(x=>(category==="All"||x.category===category)&&[x.name,x.description,x.category,...x.tags].join(" ").toLowerCase().includes(query.toLowerCase())&&(!onlySaved||saved.includes("demo:"+x.id))),[category,query,onlySaved,saved]);
 const filteredEvents=events.filter(x=>(category==="All"||category==="Events")&&(!onlySaved||saved.includes("event:"+x.id))&&[x.name,x.venue||""].join(" ").toLowerCase().includes(query.toLowerCase())&&(!x.date||when==="Any time"||(() => {const d=new Date(x.date!),now=new Date();if(Number.isNaN(d.getTime()))return false;if(when==="Right now")return false;if(when==="Tonight")return d.toDateString()===now.toDateString();const day=now.getDay();const friday=new Date(now);friday.setDate(now.getDate()+((5-day+7)%7));friday.setHours(0,0,0,0);const monday=new Date(friday);monday.setDate(friday.getDate()+3);return d>=friday&&d<monday})()));
 function locate(){if(!navigator.geolocation){setStatus("Location is not available in this browser");return}setStatus("Finding your location…");navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lng:p.coords.longitude});setCity("My current location");setStatus("Location found. Search live events below.")},()=>setStatus("Location permission denied. You can still browse the preview."),{timeout:10000})}
 async function loadEvents(){setEventState("loading");try{const c=coords??(city.trim().toLowerCase()==="durham, nc"?DEFAULT_COORDS:null);if(!c){setEventState("location");return}const res=await fetch("/api/events?lat="+encodeURIComponent(c.lat)+"&lng="+encodeURIComponent(c.lng));const data=await res.json();if(!res.ok)throw Error(data.error||"Event service unavailable");setEvents(data.events||[]);setEventState(data.configured?"ready":"unconfigured")}catch{setEventState("error")}}
 return <main className="gradient min-h-screen"><header className="mx-auto max-w-7xl px-5 py-6 flex items-center justify-between"><div className="flex items-center gap-2 text-2xl font-black tracking-tight"><Compass className="text-violet-400"/>roam<span className="text-violet-400">.</span></div><span className="text-sm text-slate-400">Discover your world</span></header>
 <section className="mx-auto max-w-7xl px-5 pt-12 pb-10"><div className="inline-flex items-center gap-2 text-violet-300 text-sm mb-5"><Sparkles size={16}/> YOUR NEXT STORY STARTS HERE</div><h1 className="max-w-3xl text-5xl md:text-7xl font-black tracking-tight leading-[1.05]">Go somewhere.<br/><span className="text-violet-400">Do something.</span></h1><p className="text-slate-400 text-lg mt-6 max-w-2xl">Find experiences, great food, live events and hidden gems wherever you are.</p>
 <div className="glass mt-9 rounded-2xl p-4 max-w-4xl grid gap-3 md:grid-cols-[1fr_1.5fr_auto]"><label className="flex items-center gap-2 rounded-xl bg-[#101626] px-4"><MapPin className="text-violet-400" size={20}/><input aria-label="City or location" value={city} onChange={e=>{setCity(e.target.value);setCoords(null)}} className="bg-transparent w-full py-4 outline-none" placeholder="City or ZIP code"/></label><label className="flex items-center gap-2 rounded-xl bg-[#101626] px-4"><Search className="text-slate-400" size={20}/><input aria-label="Search experiences" value={query} onChange={e=>setQuery(e.target.value)} className="bg-transparent w-full py-4 outline-none" placeholder="What are you in the mood for?"/></label><button onClick={locate} className="bg-violet-400 text-slate-950 rounded-xl px-5 py-3 font-bold flex items-center justify-center gap-2"><LocateFixed size={19}/> Locate</button></div>{status&&<p role="status" className="text-xs text-slate-400 mt-2">{status}</p>}
 <div className="mt-6 flex gap-2 flex-wrap">{["Any time","Right now","Tonight","This weekend"].map(t=><button key={t} className="pill text-sm" data-active={when===t} onClick={()=>setWhen(t)}><Clock3 className="inline mr-2" size={14}/>{t}</button>)}</div></section>
 <section className="mx-auto max-w-7xl px-5 pb-20"><div className="flex flex-wrap justify-between items-center gap-3 mb-5"><h2 className="text-2xl font-bold">Explore experiences</h2><button onClick={()=>setOnlySaved(v=>!v)} className="pill text-sm" data-active={onlySaved}><Heart size={16} className="inline mr-2"/>Saved ({saved.length})</button></div><div className="flex flex-wrap gap-2 mb-7">{categories.map(c=><button key={c} className="pill text-sm" data-active={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div className="glass rounded-2xl p-5 mb-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold flex items-center gap-2"><CalendarDays size={18} className="text-violet-400"/> Live event discovery</h3><p className="text-slate-400 text-sm mt-1">Real event data when a provider is connected. Durham is the default demo city; elsewhere use your current location.</p></div><button onClick={loadEvents} disabled={eventState==="loading"} className="bg-violet-400 disabled:opacity-50 text-slate-950 rounded-xl px-5 py-3 font-bold flex items-center gap-2"><RefreshCw size={16}/>{eventState==="loading"?"Searching…":"Find live events"}</button></div>{eventState==="unconfigured"&&<p role="status" className="mt-3 text-amber-200 text-sm">Live event integration is awaiting a server-side API key. No events are being invented.</p>}{eventState==="location"&&<p role="status" className="mt-3 text-amber-200 text-sm">Use Locate to search outside Durham.</p>}{eventState==="error"&&<p role="status" className="mt-3 text-amber-200 text-sm">The event provider could not be reached. Try again later.</p>}{eventState==="ready"&&<p role="status" className="mt-3 text-slate-300 text-sm">{events.length} events returned by the provider. Availability and details may change.</p>}</div>
 {filteredEvents.length>0&&<><h3 className="text-xl font-bold mb-4">Upcoming events</h3><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 mb-10">{filteredEvents.map(e=><article className="card" key={e.id}>{e.image?<img src={e.image} alt="" className="h-44 w-full object-cover"/>:<div className="h-44 bg-violet-950 flex items-center justify-center text-5xl">🎟️</div>}<div className="p-5"><div className="text-violet-300 text-xs">Ticketmaster · {e.date?new Date(e.date).toLocaleString():"Date TBD"}</div><h3 className="font-bold text-xl mt-2">{e.name}</h3><p className="text-slate-400 text-sm mt-2">{e.venue||"Venue not provided"}</p><div className="flex justify-between items-center mt-5"><button aria-label="Save event" onClick={()=>toggleSaved("event:"+e.id)} className="text-violet-300"><Heart fill={saved.includes("event:"+e.id)?"currentColor":"none"}/></button>{e.url&&<a href={e.url} target="_blank" rel="noopener noreferrer" className="text-violet-300 text-sm flex gap-1 items-center">Details <ExternalLink size={14}/></a>}</div></div></article>)}</div></>}
 <div className="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 text-amber-100 px-4 py-3 text-sm">Explore ideas below are examples, not verified businesses or live opening hours. Time filters only apply to dated provider events.</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{listings.map(x=><article className="card" key={x.id}><div className="h-44 flex items-center justify-center text-7xl" style={{background:x.image}} aria-hidden="true">{x.emoji}</div><div className="p-5"><div className="flex items-center justify-between text-xs text-violet-300"><span>{x.category}</span><span>{x.price}</span></div><h3 className="font-bold text-xl mt-3">{x.name}</h3><p className="text-slate-400 text-sm mt-2 min-h-10">{x.description}</p><div className="flex items-center justify-between mt-5 text-sm"><span className="text-slate-500"><MapPin size={14} className="inline"/> {x.neighborhood}</span><button aria-label={"Save "+x.name} onClick={()=>toggleSaved("demo:"+x.id)} className="text-violet-300 flex gap-1 items-center"><Heart size={17} fill={saved.includes("demo:"+x.id)?"currentColor":"none"}/>{saved.includes("demo:"+x.id)?"Saved":"Save"}</button></div></div></article>)}</div>{listings.length===0&&filteredEvents.length===0&&<p className="text-slate-400 py-12">No matching results. Try another category or clear saved-only mode.</p>}</section><footer className="border-t border-white/10 px-5 py-8 text-center text-sm text-slate-500">ROAM · Early access preview · Verify event details with the organizer</footer></main>;
}
