"use client";
import {useState} from "react";
import {MapPin,Compass,Sparkles,LocateFixed} from "lucide-react";
import UnifiedDiscover from "../components/UnifiedDiscover";
export default function Home(){
 const [city,setCity]=useState("Durham, NC"),[status,setStatus]=useState(""),[coords,setCoords]=useState<{lat:number;lng:number}|null>(null);
 function locate(){if(!navigator.geolocation){setStatus("Location is not available in this browser");return}setStatus("Finding your location…");navigator.geolocation.getCurrentPosition(p=>{setCoords({lat:p.coords.latitude,lng:p.coords.longitude});setCity("My current location");setStatus("Location found. Tap Explore this area below.")},()=>setStatus("Location permission denied. You can still browse the preview."),{timeout:10000})}
 return <main className="gradient min-h-screen"><header className="mx-auto max-w-7xl px-5 py-6 flex items-center justify-between"><div className="flex items-center gap-2 text-2xl font-black tracking-tight"><Compass className="text-violet-400"/>roam<span className="text-violet-400">.</span></div><span className="text-sm text-slate-400">Discover your world</span></header>
 <section className="mx-auto max-w-7xl px-5 pt-12 pb-10"><div className="inline-flex items-center gap-2 text-violet-300 text-sm mb-5"><Sparkles size={16}/> DISCOVER WHAT’S NEARBY</div><h1 className="max-w-3xl text-5xl md:text-7xl font-black tracking-tight leading-[1.05]">Go somewhere.<br/><span className="text-violet-400">Do something.</span></h1><p className="text-slate-400 text-lg mt-6 max-w-2xl">Restaurants, cocktails, events and experiences worth leaving the house for.</p>
 <div className="glass mt-9 rounded-2xl p-4 max-w-4xl grid gap-3 md:grid-cols-[1fr_auto]"><label className="flex items-center gap-2 rounded-xl bg-[#101626] px-4"><MapPin className="text-violet-400" size={20}/><input aria-label="City or location" value={city} onChange={e=>{setCity(e.target.value);setCoords(null)}} className="bg-transparent w-full py-4 outline-none" placeholder="City or ZIP code"/></label><button onClick={locate} className="bg-violet-400 text-slate-950 rounded-xl px-5 py-3 font-bold flex items-center justify-center gap-2"><LocateFixed size={19}/> Locate</button></div>{status&&<p role="status" className="text-xs text-slate-400 mt-2">{status}</p>}
 </section>
 <section className="mx-auto max-w-7xl px-5 pb-20"><UnifiedDiscover coords={coords} city={city}/></section><footer className="border-t border-white/10 px-5 py-8 text-center text-sm text-slate-500">ROAM · Early access preview · Verify event details with the organizer</footer></main>;
}
