"use client";
import {useState} from "react";
import {MapPin,ExternalLink,RefreshCw,Navigation} from "lucide-react";
type Place={id:string;name:string;category:string;latitude:number;longitude:number;address:string|null;website:string|null;openingHours:string|null;sourceUrl:string};
export default function NearbyPlaces({coords,city}:{coords:{lat:number;lng:number}|null;city:string}){
 const [places,setPlaces]=useState<Place[]>([]),[status,setStatus]=useState("idle"),[category,setCategory]=useState("All");
 const durham=city.trim().toLowerCase()==="durham, nc";
 async function search(){const c=coords??(durham?{lat:35.994,lng:-78.899}:null);if(!c){setStatus("location");return}setStatus("loading");try{const r=await fetch("/api/places?lat="+c.lat+"&lng="+c.lng);const j=await r.json();if(!r.ok)throw Error();setPlaces(j.places??[]);setStatus("ready")}catch{setStatus("error")}}
 const shown=places.filter(p=>category==="All"||p.category===category).slice(0,24);
 return <section className="mt-12 mb-10"><div className="flex flex-wrap justify-between items-center gap-3 mb-3"><div><h2 className="text-2xl font-bold">Real places nearby</h2><p className="text-slate-400 text-sm mt-1">Discover mapped restaurants, attractions and activities using OpenStreetMap.</p></div><button onClick={search} disabled={status==="loading"} className="bg-violet-400 disabled:opacity-50 text-slate-950 rounded-xl px-5 py-3 font-bold flex items-center gap-2"><RefreshCw size={16}/>{status==="loading"?"Searching…":"Find places"}</button></div>
 <p className="text-xs text-slate-500 mb-5">Locations are mapped, not verified as open now. Details may be incomplete. © OpenStreetMap contributors.</p>
 {status==="location"&&<p role="status" className="text-amber-200 text-sm mb-4">Use the Locate button above to find places outside Durham.</p>}{status==="error"&&<p role="status" className="text-amber-200 text-sm mb-4">Places data is temporarily unavailable. Try again later.</p>}{status==="ready"&&<p role="status" className="text-slate-400 text-sm mb-4">{places.length} mapped places returned.</p>}
 {places.length>0&&<><div className="flex gap-2 flex-wrap mb-5">{["All","Food & Drink","Nightlife","Activities","Attractions"].map(c=><button key={c} className="pill text-sm" data-active={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{shown.map(p=><article key={p.id} className="card p-5"><div className="text-xs text-violet-300">{p.category}</div><h3 className="font-bold text-lg mt-2">{p.name}</h3><p className="text-slate-400 text-sm mt-2 flex items-start gap-1"><MapPin size={15} className="shrink-0"/>{p.address||"Address not listed"}</p><div className="mt-5 flex justify-between gap-3"><a href={p.sourceUrl} target="_blank" rel="noopener noreferrer" className="text-violet-300 text-sm flex items-center gap-1">Map details <ExternalLink size={14}/></a><a href={`https://www.google.com/maps/dir/?api=1&destination=${p.latitude},${p.longitude}`} target="_blank" rel="noopener noreferrer" className="text-violet-300 text-sm flex items-center gap-1"><Navigation size={14}/>Directions</a></div></article>)}</div>{shown.length===0&&<p className="text-slate-400">No places in this category.</p>}</>}
 </section>;
}
