"use client";
import {useMemo,useState} from "react";
import {Clock3,Sparkles,MapPin,ExternalLink} from "lucide-react";
import {buildSuggestedPlan,type PlanCandidate,type PlanPreferences} from "../lib/night-planner";
export default function NightPlanner({items}:{items:PlanCandidate[]}){
 const [hours,setHours]=useState(4),[vibe,setVibe]=useState<PlanPreferences["vibe"]>("balanced"),[generated,setGenerated]=useState(false),[start,setStart]=useState("");
 const plan=useMemo(()=>generated?buildSuggestedPlan(items,{hours,vibe,startAt:start}):[],[items,hours,vibe,generated,start]);
 function generate(){setStart(new Date().toISOString());setGenerated(true)}
 return <div className="glass rounded-2xl p-5 mt-8"><div className="flex gap-2 items-center"><Sparkles className="text-violet-400"/><h3 className="text-xl font-bold">Build my night</h3></div><p className="text-slate-400 text-sm mt-2">Get a suggested route using mapped places returned by your search.</p><div className="grid sm:grid-cols-2 gap-3 mt-5"><label className="text-sm text-slate-300">Time available<select value={hours} onChange={e=>{setHours(Number(e.target.value));setGenerated(false)}} className="block mt-2 w-full bg-[#101626] p-3 rounded-xl">{[2,3,4,5,6,8].map(h=><option key={h} value={h}>{h} hours</option>)}</select></label><label className="text-sm text-slate-300">Your vibe<select value={vibe} onChange={e=>{setVibe(e.target.value as PlanPreferences["vibe"]);setGenerated(false)}} className="block mt-2 w-full bg-[#101626] p-3 rounded-xl"><option value="balanced">A little of everything</option><option value="food">Food & drinks</option><option value="activities">Games & activities</option><option value="nightlife">Nightlife</option></select></label></div><button onClick={generate} disabled={!items.some(x=>x.kind==="place")} className="mt-4 bg-violet-400 disabled:opacity-40 text-slate-950 font-bold rounded-xl px-5 py-3">Generate itinerary</button>{generated&&<div className="mt-6"><p className="text-amber-200 text-sm mb-4">Suggested timing only. Hours, admission, travel times, reservations and event availability have not been verified. Allow extra time for transportation.</p>{plan.length===0?<p className="text-slate-400 text-sm">Not enough nearby places to build a plan. Try a different location.</p>:<ol className="space-y-3">{plan.map((s,i)=><li key={s.item.id} className="bg-[#101626] rounded-xl p-4 flex gap-3"><span className="text-violet-300 font-bold">{i+1}.</span><div className="flex-1"><h4 className="font-bold">{s.item.title}</h4><p className="text-slate-400 text-sm mt-1"><Clock3 size={13} className="inline mr-1"/>{new Date(s.time).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})} · Approx. {s.durationMinutes} min</p><p className="text-slate-400 text-xs mt-1">{s.item.category}</p>{s.item.url&&<a href={s.item.url} target="_blank" rel="noopener noreferrer" className="text-violet-300 text-sm inline-flex gap-1 items-center mt-2">Place details <ExternalLink size={13}/></a>}</div></li>)}</ol>}</div>}</div>;
}
