"use client";
import {useMemo,useState} from "react";
import {CalendarDays,MapPin,Navigation,Search,RefreshCw,ExternalLink,Sparkles,X} from "lucide-react";
import {dedupeRecords,rankRecord,safeHttpUrl} from "../lib/discovery-engine";
import NightPlanner from "./NightPlanner";
import {matchesIntent,type DiscoveryCategory} from "../lib/discovery-intents";
import {breakfastConfidence,breakfastDisclosure} from "../lib/breakfast-confidence";
import {freshnessDescription,sourceDisclosure} from "../lib/source-confidence";
type Coord={lat:number;lng:number};
type Result={id:string;title:string;kind:"place"|"event";category:string;subtitle:string;url:string|null;lat?:number;lng?:number;start?:string|null;distance?:number;score:number;source:string;openingHours?:string|null;website?:string|null;cuisine?:string|null;breakfast?:string|null;lastFetchedAt?:string|null;hoursAssessment?:{state:"likely_open"|"likely_closed"|"unknown";reason:string;timezone:string|null}};
function distance(a:Coord,b:Coord){const rad=Math.PI/180,dlat=(b.lat-a.lat)*rad,dlng=(b.lng-a.lng)*rad;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlng/2)**2;return 3958.76*2*Math.asin(Math.min(1,Math.sqrt(h)))}
export default function UnifiedDiscover({city,coords}:{city:string;coords:Coord|null}){
 const [openFilter,setOpenFilter]=useState(false);const [kind,setKind]=useState<"All"|"Places"|"Events">("All");const [radius,setRadius]=useState(1800);const [quickIntent,setQuickIntent]=useState<DiscoveryCategory|null>(null);const [showAdvanced,setShowAdvanced]=useState(false);const [coverage,setCoverage]=useState<{places:number;events:number;withListedHours:number;withWebsite:number;unknownHours:number}|null>(null);const [surprise,setSurprise]=useState<Result|null>(null);const [items,setItems]=useState<Result[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[sort,setSort]=useState("Recommended"),[when,setWhen]=useState("Any time"),[center,setCenter]=useState<Coord|null>(null);
 async function search(){setLoading(true);setMessage("");setItems([]);setSurprise(null);setCoverage(null);try{
  let c=coords;if(!c){const geo=await fetch("/api/geocode?q="+encodeURIComponent(city));const j=await geo.json();if(!geo.ok||!j.results?.length)throw Error("We couldn't find that city or ZIP code.");c={lat:j.results[0].lat,lng:j.results[0].lng}}setCenter(c);
  const response=await fetch("/api/unified?lat="+c.lat+"&lng="+c.lng+"&radius="+radius);
  if(!response.ok)throw Error("Discovery services are temporarily unavailable");
  const data=await response.json();
  const notes:string[]=data.warnings??[];setCoverage(data.coverage??null);
  const places:Result[]=(data.places??[]).map((x:any)=>{const d=distance(c!,{lat:x.latitude,lng:x.longitude});return {id:"place:"+x.id,title:x.name,kind:"place" as const,category:x.category,subtitle:x.address||"Address unavailable",url:x.sourceUrl,lat:x.latitude,lng:x.longitude,distance:d,score:0,source:"OpenStreetMap",openingHours:x.openingHours,website:x.website,cuisine:x.cuisine,breakfast:x.breakfast,lastFetchedAt:x.lastFetchedAt,hoursAssessment:x.hoursAssessment}});
  const events:Result[]=(data.events??[]).map((x:any)=>({id:"event:"+x.id,title:x.name,kind:"event" as const,category:"Events",subtitle:x.venue||"Venue not listed",url:x.url,start:x.date,score:0,source:"Ticketmaster"}));
  const combined=dedupeRecords([...places,...events].map(x=>({...x,startsAt:x.start,latitude:x.lat,longitude:x.lng,sourceUrl:x.url,distanceMiles:x.distance}))).map(x=>({...x,score:rankRecord(x)}));setItems(combined);setMessage(notes.length?notes.join(" · "):"Results loaded. Select Breakfast to explore likely morning spots");
 }catch(e){setMessage(e instanceof Error?e.message:"Discovery is temporarily unavailable")}finally{setLoading(false)}}
 const results=useMemo(()=>{const q=query.toLocaleLowerCase().trim();const now=new Date();return items.filter(x=>(!quickIntent||(x.kind==="place"&&matchesIntent(x,quickIntent)))&&(!openFilter||(x.kind==="place"&&x.hoursAssessment?.state==="likely_open"))&&(kind==="All"||(kind==="Places"?x.kind==="place":x.kind==="event"))&&(category==="All"||x.category===category)&&(!q||[x.title,x.subtitle,x.category].join(" ").toLocaleLowerCase().includes(q))&&(when==="Any time"||x.kind==="place"||(x.start&&(()=>{const d=new Date(x.start!);if(Number.isNaN(d.getTime()))return false;if(when==="Right now")return false;if(when==="Tonight")return d.toDateString()===now.toDateString();const friday=new Date(now);friday.setDate(now.getDate()+((5-now.getDay()+7)%7));friday.setHours(0,0,0,0);const monday=new Date(friday);monday.setDate(friday.getDate()+3);return d>=friday&&d<monday})()))).sort((a,b)=>sort==="Nearest"?(a.distance??Infinity)-(b.distance??Infinity):sort==="Soonest"?(Date.parse(a.start||"")||Infinity)-(Date.parse(b.start||"")||Infinity):b.score-a.score)},[items,quickIntent,openFilter,kind,category,query,when,sort]);
 return <section className="mt-12 mb-12" id="discover"><div className="glass rounded-3xl p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-violet-300 text-xs tracking-widest font-bold">FIND YOUR NEXT EXPERIENCE</p><h2 className="text-3xl font-bold mt-2">What are we doing?</h2><p className="text-slate-400 text-sm mt-2">Find breakfast, food, drinks, activities and events nearby.</p></div><button disabled={loading} onClick={search} className="bg-violet-400 disabled:opacity-50 text-slate-950 font-bold px-6 py-3 rounded-xl flex gap-2 items-center"><RefreshCw size={17}/>{loading?"Searching…":"Explore this area"}</button></div>
 <div className="mt-6"><label className="bg-[#101626] rounded-xl px-4 flex items-center gap-2"><Search size={18} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cocktails, arcades, date night, restaurants…" aria-label="Search results" className="bg-transparent py-4 w-full outline-none"/></label></div><div className="mt-4 flex flex-wrap gap-2">{(["Breakfast","Drinks","Games","Restaurants","Museums"] as DiscoveryCategory[]).map(term=><button key={term} data-active={quickIntent===term} onClick={()=>{setQuickIntent(old=>old===term?null:term);setQuery("");setCategory("All");setKind("All")}} className="pill text-xs">{term}</button>)}{quickIntent&&<button className="pill text-xs" onClick={()=>setQuickIntent(null)}>Clear selection</button>}<button onClick={()=>setShowAdvanced(v=>!v)} className="pill text-xs">{showAdvanced?"Fewer filters":"More filters"}</button></div>{showAdvanced&&<div className="grid sm:grid-cols-2 gap-3 mt-4"><select aria-label="Sort results" value={sort} onChange={e=>setSort(e.target.value)} className="bg-[#101626] rounded-xl px-4 py-3"><option>Recommended</option><option>Nearest</option><option>Soonest</option></select><select aria-label="When" value={when} onChange={e=>setWhen(e.target.value)} className="bg-[#101626] rounded-xl px-4 py-3">{["Any time","Right now","Tonight","This weekend"].map(t=><option key={t}>{t}</option>)}</select></div>}<div className="flex flex-wrap gap-2 mt-4">{["All","Food & Drink","Nightlife","Activities","Attractions","Events"].map(c=><button key={c} className="pill text-xs" data-active={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div className="flex flex-wrap gap-2 mt-4"><button disabled={!results.length} onClick={()=>setSurprise(results[Math.floor(Math.random()*results.length)])} className="pill text-sm disabled:opacity-40 flex items-center gap-2"><Sparkles size={16}/> Surprise me</button>{surprise&&<button className="pill text-sm" onClick={()=>setSurprise(null)}><X size={14} className="inline mr-1"/> Clear pick</button>}</div>{surprise&&<div className="rounded-2xl border border-violet-400/40 bg-violet-500/10 p-5 mt-4"><p className="text-xs text-violet-300 font-bold">YOUR RANDOM DISCOVERY PICK</p><h3 className="text-xl font-bold mt-2">{surprise.title}</h3><p className="text-slate-300 text-sm mt-1">{surprise.category} · {surprise.subtitle}</p><p className="text-slate-400 text-xs mt-2">Random selection from currently loaded results; opening hours and availability are not verified.</p>{safeHttpUrl(surprise.url)&&<a href={safeHttpUrl(surprise.url)!} target="_blank" rel="noopener noreferrer" className="inline-flex text-violet-300 text-sm mt-3 gap-1 items-center">Explore details <ExternalLink size={14}/></a>}</div>}{coverage&&<div className="mt-5 grid grid-cols-2 md:grid-cols-4 gap-2">{[["Mapped places",coverage.places],["Events",coverage.events],["Hours listed",coverage.withListedHours],["Websites listed",coverage.withWebsite]].map(([label,value])=><div key={String(label)} className="bg-[#101626] border border-white/10 rounded-xl p-3"><div className="text-xl font-bold">{value}</div><div className="text-xs text-slate-400 mt-1">{label}</div></div>)}</div>}<p role="status" className="text-slate-400 text-sm mt-4">{loading?"Looking up nearby places and events…":message}</p>
 {items.length>0&&<><p className="text-slate-400 text-xs my-4">{results.length} results · Places are not verified open now; events have provider-supplied dates. Sorting is approximate. © OpenStreetMap contributors.</p><div className="grid md:grid-cols-2 gap-3 max-h-[650px] overflow-y-auto">{results.slice(0,80).map(x=><article key={x.id} className="bg-[#101626] border border-white/10 rounded-xl p-4"><div className="flex items-center justify-between gap-2"><span className="text-violet-300 text-xs flex items-center gap-1">{x.kind==="event"?<CalendarDays size={14}/>:<MapPin size={14}/>} {x.category}</span>{x.distance!==undefined&&<span className="text-slate-400 text-xs">{x.distance.toFixed(1)} mi</span>}</div><h3 className="font-bold mt-2">{x.title}</h3><p className="text-slate-400 text-sm mt-1">{x.subtitle}</p>{quickIntent==="Breakfast"&&x.kind==="place"&&<p className="text-amber-200 text-xs mt-2">{breakfastDisclosure(breakfastConfidence(x))}</p>}{x.kind==="place"&&<div className="mt-2 text-xs text-slate-400">{x.openingHours?<p>Listed hours: {x.openingHours}</p>:<p>Opening hours not provided</p>}<p className={x.hoursAssessment?.state==="likely_open"?"text-emerald-300":x.hoursAssessment?.state==="likely_closed"?"text-orange-300":"text-slate-400"}>{x.hoursAssessment?.state==="likely_open"?"Likely open based on mapped hours":x.hoursAssessment?.state==="likely_closed"?"Likely closed based on mapped hours":"Open status unknown"}</p><p>{x.hoursAssessment?.reason||"Opening status not available"}</p>{x.lastFetchedAt&&<p>{freshnessDescription(x.lastFetchedAt)}</p>}<p>{sourceDisclosure(x.source)}</p></div>}{x.start&&<p className="text-slate-400 text-xs mt-1">{new Date(x.start).toLocaleString()}</p>}<div className="flex flex-wrap gap-4 mt-4">{safeHttpUrl(x.url)&&<a className="text-violet-300 text-sm flex items-center gap-1" target="_blank" rel="noopener noreferrer" href={safeHttpUrl(x.url)!}>Details <ExternalLink size={14}/></a>}{safeHttpUrl(x.website)&&<a className="text-violet-300 text-sm flex items-center gap-1" target="_blank" rel="noopener noreferrer" href={safeHttpUrl(x.website)!}>Website <ExternalLink size={14}/></a>}{x.lat!==undefined&&x.lng!==undefined&&<a className="text-violet-300 text-sm flex items-center gap-1" target="_blank" rel="noopener noreferrer" href={"https://www.google.com/maps/dir/?api=1&destination="+x.lat+","+x.lng}><Navigation size={14}/>Directions</a>}</div></article>)}</div></>}
 {items.length>0&&<NightPlanner items={results.map(x=>({id:x.id,title:x.title,kind:x.kind,category:x.category,start:x.start,distance:x.distance,url:safeHttpUrl(x.url)}))}/>}{items.length>0&&results.length===0&&<p className="py-8 text-slate-400">No results match these filters. Try another category or time.</p>}</div></section>;
}
