"use client";
import {useMemo,useState} from "react";
import {CalendarDays,MapPin,Navigation,Search,RefreshCw,ExternalLink,Sparkles,X} from "lucide-react";
import {dedupeRecords,rankRecord,safeHttpUrl} from "../lib/discovery-engine";
import NightPlanner from "./NightPlanner";
type Coord={lat:number;lng:number};
type Result={id:string;title:string;kind:"place"|"event";category:string;subtitle:string;url:string|null;lat?:number;lng?:number;start?:string|null;distance?:number;score:number;source:string};
function distance(a:Coord,b:Coord){const rad=Math.PI/180,dlat=(b.lat-a.lat)*rad,dlng=(b.lng-a.lng)*rad;const h=Math.sin(dlat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dlng/2)**2;return 3958.76*2*Math.asin(Math.min(1,Math.sqrt(h)))}
export default function UnifiedDiscover({city,coords}:{city:string;coords:Coord|null}){
 const [surprise,setSurprise]=useState<Result|null>(null);const [items,setItems]=useState<Result[]>([]),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[sort,setSort]=useState("Recommended"),[when,setWhen]=useState("Any time"),[center,setCenter]=useState<Coord|null>(null);
 async function search(){setLoading(true);setMessage("");setItems([]);setSurprise(null);try{
  let c=coords;if(!c){const geo=await fetch("/api/geocode?q="+encodeURIComponent(city));const j=await geo.json();if(!geo.ok||!j.results?.length)throw Error("We couldn't find that city or ZIP code.");c={lat:j.results[0].lat,lng:j.results[0].lng}}setCenter(c);
  const response=await fetch("/api/unified?lat="+c.lat+"&lng="+c.lng);
  if(!response.ok)throw Error("Discovery services are temporarily unavailable");
  const data=await response.json();
  const notes:string[]=data.warnings??[];
  const places:Result[]=(data.places??[]).map((x:any)=>{const d=distance(c!,{lat:x.latitude,lng:x.longitude});return {id:"place:"+x.id,title:x.name,kind:"place" as const,category:x.category,subtitle:x.address||"Address unavailable",url:x.sourceUrl,lat:x.latitude,lng:x.longitude,distance:d,score:0,source:"OpenStreetMap"}});
  const events:Result[]=(data.events??[]).map((x:any)=>({id:"event:"+x.id,title:x.name,kind:"event" as const,category:"Events",subtitle:x.venue||"Venue not listed",url:x.url,start:x.date,score:0,source:"Ticketmaster"}));
  const combined=dedupeRecords([...places,...events].map(x=>({...x,startsAt:x.start,latitude:x.lat,longitude:x.lng,sourceUrl:x.url,distanceMiles:x.distance}))).map(x=>({...x,score:rankRecord(x)}));setItems(combined);setMessage(notes.length?notes.join(" · "):"Results loaded from available sources");
 }catch(e){setMessage(e instanceof Error?e.message:"Discovery is temporarily unavailable")}finally{setLoading(false)}}
 const results=useMemo(()=>{const q=query.toLocaleLowerCase().trim();const now=new Date();return items.filter(x=>(category==="All"||x.category===category)&&(!q||[x.title,x.subtitle,x.category].join(" ").toLocaleLowerCase().includes(q))&&(when==="Any time"||x.kind==="place"||(x.start&&(()=>{const d=new Date(x.start!);if(Number.isNaN(d.getTime()))return false;if(when==="Right now")return false;if(when==="Tonight")return d.toDateString()===now.toDateString();const friday=new Date(now);friday.setDate(now.getDate()+((5-now.getDay()+7)%7));friday.setHours(0,0,0,0);const monday=new Date(friday);monday.setDate(friday.getDate()+3);return d>=friday&&d<monday})()))).sort((a,b)=>sort==="Nearest"?(a.distance??Infinity)-(b.distance??Infinity):sort==="Soonest"?(Date.parse(a.start||"")||Infinity)-(Date.parse(b.start||"")||Infinity):b.score-a.score)},[items,category,query,when,sort]);
 return <section className="mt-12 mb-12" id="discover"><div className="glass rounded-3xl p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-violet-300 text-xs tracking-widest font-bold">ONE SEARCH. MORE POSSIBILITIES.</p><h2 className="text-3xl font-bold mt-2">Discover everything nearby</h2><p className="text-slate-400 text-sm mt-2">Real mapped places and available event feeds, together.</p></div><button disabled={loading} onClick={search} className="bg-violet-400 disabled:opacity-50 text-slate-950 font-bold px-6 py-3 rounded-xl flex gap-2 items-center"><RefreshCw size={17}/>{loading?"Searching…":"Explore this area"}</button></div>
 <div className="mt-6 grid gap-3 md:grid-cols-3"><label className="bg-[#101626] rounded-xl px-4 flex items-center gap-2"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all results" aria-label="Search results" className="bg-transparent py-3 w-full outline-none"/></label><select aria-label="Sort results" value={sort} onChange={e=>setSort(e.target.value)} className="bg-[#101626] rounded-xl px-4 py-3"><option>Recommended</option><option>Nearest</option><option>Soonest</option></select><select aria-label="When" value={when} onChange={e=>setWhen(e.target.value)} className="bg-[#101626] rounded-xl px-4 py-3">{["Any time","Right now","Tonight","This weekend"].map(t=><option key={t}>{t}</option>)}</select></div>
 <div className="flex flex-wrap gap-2 mt-4">{["All","Food & Drink","Nightlife","Activities","Attractions","Events"].map(c=><button key={c} className="pill text-xs" data-active={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 <div className="flex flex-wrap gap-2 mt-4"><button disabled={!results.length} onClick={()=>setSurprise(results[Math.floor(Math.random()*results.length)])} className="pill text-sm disabled:opacity-40 flex items-center gap-2"><Sparkles size={16}/> Surprise me</button>{surprise&&<button className="pill text-sm" onClick={()=>setSurprise(null)}><X size={14} className="inline mr-1"/> Clear pick</button>}</div>{surprise&&<div className="rounded-2xl border border-violet-400/40 bg-violet-500/10 p-5 mt-4"><p className="text-xs text-violet-300 font-bold">YOUR RANDOM DISCOVERY PICK</p><h3 className="text-xl font-bold mt-2">{surprise.title}</h3><p className="text-slate-300 text-sm mt-1">{surprise.category} · {surprise.subtitle}</p><p className="text-slate-400 text-xs mt-2">Random selection from currently loaded results; opening hours and availability are not verified.</p>{safeHttpUrl(surprise.url)&&<a href={safeHttpUrl(surprise.url)!} target="_blank" rel="noopener noreferrer" className="inline-flex text-violet-300 text-sm mt-3 gap-1 items-center">Explore details <ExternalLink size={14}/></a>}</div>}<p role="status" className="text-slate-400 text-sm mt-4">{loading?"Looking up nearby places and events…":message}</p>
 {items.length>0&&<><p className="text-slate-400 text-xs my-4">{results.length} results · Places are not verified open now; events have provider-supplied dates. Sorting is approximate. © OpenStreetMap contributors.</p><div className="grid md:grid-cols-2 gap-3 max-h-[650px] overflow-y-auto">{results.slice(0,80).map(x=><article key={x.id} className="bg-[#101626] border border-white/10 rounded-xl p-4"><div className="flex items-center justify-between gap-2"><span className="text-violet-300 text-xs flex items-center gap-1">{x.kind==="event"?<CalendarDays size={14}/>:<MapPin size={14}/>} {x.category}</span>{x.distance!==undefined&&<span className="text-slate-400 text-xs">{x.distance.toFixed(1)} mi</span>}</div><h3 className="font-bold mt-2">{x.title}</h3><p className="text-slate-400 text-sm mt-1">{x.subtitle}</p>{x.start&&<p className="text-slate-400 text-xs mt-1">{new Date(x.start).toLocaleString()}</p>}<div className="flex flex-wrap gap-4 mt-4">{x.url&&<a className="text-violet-300 text-sm flex items-center gap-1" target="_blank" rel="noopener noreferrer" href={safeHttpUrl(x.url)??"#"}>Details <ExternalLink size={14}/></a>}{x.lat!==undefined&&x.lng!==undefined&&<a className="text-violet-300 text-sm flex items-center gap-1" target="_blank" rel="noopener noreferrer" href={"https://www.google.com/maps/dir/?api=1&destination="+x.lat+","+x.lng}><Navigation size={14}/>Directions</a>}</div></article>)}</div></>}
 {items.length>0&&<NightPlanner items={results.map(x=>({id:x.id,title:x.title,kind:x.kind,category:x.category,start:x.start,distance:x.distance,url:safeHttpUrl(x.url)}))}/>}{items.length>0&&results.length===0&&<p className="py-8 text-slate-400">No results match these filters. Try another category or time.</p>}</div></section>;
}
